[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd neural-network-frontend && npm ci --include=dev']

[phases.build]
cmds = ['cd neural-network-frontend && npm run build:prod']
dependsOn = ['install']

[start]
cmd = 'cd neural-network-frontend && node server.js'
